# Generated by Django 3.2.7 on 2021-09-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
